import { MarketingNav } from "@/components/MarketingNav";
import { MarketingFooter } from "@/components/MarketingFooter";

const LAST_UPDATED = "August 18, 2026";

const SECTIONS = [
  {
    title: "1. What this document is",
    body: [
      "This is a working draft of MENTA's Terms of Service, written by the team building the product so early users know the ground rules before we launch publicly. It has not been reviewed by an attorney and is not yet a binding legal agreement. It will be replaced by a final, attorney-reviewed version before MENTA is available to the general public.",
    ],
  },
  {
    title: "2. Beta access",
    body: [
      "MENTA is currently in beta. Features may change, break, or be removed without notice. Access is free during the beta; pricing for a full product has not been finalized.",
    ],
  },
  {
    title: "3. Who can use MENTA",
    body: [
      "MENTA is built for middle-school through college athletes, coaches, trainers, and parents/guardians. If you're under 18, a parent or guardian should be involved in setting up and reviewing your account. By creating an account you're confirming the account information you provide is accurate.",
    ],
  },
  {
    title: "4. Your content",
    body: [
      "You own what you create — your profile, film, training logs, messages, and other content. By posting content that's visible to a team or another user (e.g., a message, a team calendar event), you're granting MENTA the ability to store and display it to the people it's meant for. We don't claim ownership of your content and don't sell it.",
    ],
  },
  {
    title: "5. Acceptable use",
    body: [
      "Don't use MENTA to harass, impersonate, or share another person's private information without consent. Don't upload content you don't have the right to share. Don't attempt to access another user's account or data you're not authorized to see. Messages support blocking and reporting another user — reports are reviewed by the team.",
    ],
  },
  {
    title: "6. Not medical, legal, or recruiting advice",
    body: [
      "MENTA Recovery is a wellness/training-load tracker, not a medical system — nothing in it means you're medically cleared to play. MENTA Safety is an organizational preparedness tool, not a medical or emergency-prediction system — in a real emergency, call 911. MENTA's recruiting tools help you organize outreach; they are not a guarantee of recruiting outcomes and haven't been reviewed by an NCAA compliance attorney. MENTA AI is instructed never to give medical clearance, legal advice, or a recruiting guarantee, and to say when it doesn't have information rather than invent it.",
    ],
  },
  {
    title: "7. AI features",
    body: [
      "AI features (chat, study help, outreach drafting) are generated by a third-party AI provider based on a limited slice of your own data. Review anything AI-drafted before you rely on it or send it to someone else — MENTA AI can be wrong, and it never sends messages on your behalf. If no AI provider is configured on a given deployment, the app will say so rather than fabricate a response.",
    ],
  },
  {
    title: "8. Account & termination",
    body: [
      "You're responsible for keeping your password secure and for activity on your account. We may suspend or terminate accounts that violate these terms or that we reasonably believe put another user's safety at risk. You can stop using MENTA at any time; see the Privacy Policy for how to request deletion of your data.",
    ],
  },
  {
    title: "9. No warranty",
    body: [
      "MENTA is provided as-is during the beta, without warranty of any kind. We work to keep it accurate and reliable, but we don't guarantee it will be error-free or uninterrupted.",
    ],
  },
  {
    title: "10. Changes to these terms",
    body: [
      "Because this is a pre-launch draft, it may change as features are built or removed. We'll update the date at the top of this page when it does.",
    ],
  },
];

export default function TermsPage() {
  return (
    <>
      <MarketingNav />
      <main className="px-6 md:px-10 pt-32 pb-20 max-w-2xl mx-auto">
        <div className="eyebrow justify-center flex mx-auto w-fit mb-2">Legal — Draft</div>
        <h1 className="text-4xl font-semibold mb-4 text-center">Terms of Service</h1>
        <p className="text-text-2 text-sm text-center mb-2">Last updated: {LAST_UPDATED}</p>
        <p className="card p-4 text-sm text-text-2 mb-10" style={{ borderColor: "var(--warning)" }}>
          <strong>This is a working draft, not a finished legal document.</strong> It has not been reviewed
          by an attorney and will be replaced before MENTA is available to the general public.
        </p>
        <div className="space-y-6">
          {SECTIONS.map((s) => (
            <div key={s.title} className="card p-5">
              <div className="font-heading font-semibold mb-3">{s.title}</div>
              <div className="space-y-2 text-text-2 text-sm">
                {s.body.map((p) => (
                  <p key={p}>{p}</p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </main>
      <MarketingFooter />
    </>
  );
}
